import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import style from '@/styles/about.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@600&display=swap" rel="stylesheet"/>
      </Head>
     
      
      <main  className={style.container}>
        
        <div className={style.icon}>
           <div className={style.circle} ></div>
            <img className={style.blackcat}  src='/Screenshot 2023-06-11 150834_preview_rev_1.png' />
            </div>
            <div className={style.righttext}>
              <u className={style.underline}>About The Website</u>  
            <div className={`${style.box} ${style.aboutbox}`}>
              At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellatSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium . Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam dolor illo tempora exercitationem soluta facere, impedit rerum odit nam nostrum.
            </div>
            </div>
            <div className={style.us}>
            <u className={`${style.underline} ${style.creator}`}>Creators</u>
            <div className={`${style.box} ${style.creatinfo} ${style.hinfo}`} >
            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.  
            </div>
            <div className={`${style.box} ${style.creatinfo} ${style.kinfo}`} >
            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.  
            </div>
            </div>
            <div className={style.ourphotos}>
              <img className={`${style.image} ${style.Harsh}`}  src='/Ellipse 2.png' alt="Harsh Sinha" />
              <img className={`${style.image} ${style.Kaushiki}`}  src='/Ellipse 3.png' alt="Kaushiki" />
            </div>
            
            
            
      </main>
    </>
  )
}