import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import style from '@/styles/main.module.css'

import { Outfit } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;200;600&display=swap" rel="stylesheet"></link>

      </Head>
      <style jsx>{`
  body {
    background: #0B2447;
  }
`}</style>

      <main className={style.body}>
     
        <div className={style.icon}>
           <div className={style.circle} ></div>
            <img className={style.blackcat}  src='/Screenshot 2023-06-11 150834_preview_rev_1.png' />
            </div>
            <div className={style.whatever}>
            <p className={style.para}>
              Explore <span style={{color:"#A089E0"}}>GitHub</span><br/>
              Like Never before<br/>
              <span className={style.description}> Search for repositories that speak your<br/> language, unlock hidden gems, and<br/> connect with a vibrant community of<br/> developers worldwide.<br/></span>
              <button  className={style.button}  >Learn More</button>
            </p>
            
            </div>
            
            
            
            
      </main>
    </>
  )
}